### ISSUE TITLE
Clarify dynamic and static types

### ISSUE THREAD

**Issue by jawn** [rinkkasatiainen/connascence-tictactoe#1]
If I understand correctly, 

These are dynamic: CoI, CoV, CoT, CoEO

And these are static: CoM, CoP, CoA

It would be great it that was more obvious from the visual, eg by adding boundaries.
![image](https://user-images.githubusercontent.com/1705112/68991943-baaeef80-0864-11ea-99d8-0b4350ab68ca.png)

**Comment by rinkkasatiainen** [comment]
I updated a new version of the PDF. Does that make it clear enough?

**Comment by jawn** [comment]
Perfect, thanks!
