### ISSUE TITLE
Use consistent abbreviation for Order of Execution

### ISSUE THREAD

**Issue by jawn** [rinkkasatiainen/connascence-tictactoe#2]
![image](https://user-images.githubusercontent.com/1705112/68991992-5b9daa80-0865-11ea-858e-919373db4aff.png)

vs

![image](https://user-images.githubusercontent.com/1705112/68992000-77a14c00-0865-11ea-83ba-f7fde09f853e.png)

**Comment by rinkkasatiainen** [comment]
Updated the PDF with this change.
